### ISSUE TITLE
fr-CA make it case insensitive

### ISSUE THREAD

**Issue by mindkind** [Zuntie/fivem-serverlist-api#10]
async function fetchServersByLocale(target) {
  const resolved = await Promise.all(Object.values(servers));
  return resolved.filter(srv => srv.Data?.vars?.locale?.toLowerCase() === target.toLowerCase());
}

**Comment by Zuntie** [comment]
Thanks for opening the issue!
The function has been updated and is now case-insensitive for locale comparison.
[12eedfa](https://github.com/Zuntie/fivem-serverlist-api/commit/12eedfab2e214cb83915b5e2b3a2ca2978073516)
